server:
  port: 8989
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://116.196.91.220:3306/jeicms?characterEncoding=utf-8&useSSL=false 
    username: root
    password: hSw.23ms
    initial-size: 5
    min-idle: 5
    max-active: 20
    #连接等待超时时间
    max-wait: 60000
    #配置隔多久进行一次检测(检测可以关闭的空闲连接)
    time-between-eviction-runs-millis: 60000
    #配置连接在池中的最小生存时间
    min-evictable-idle-time-millis: 30000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    
  rabbitmq:
    host: 116.196.91.220
    port: 5672
    username: admin
    password: admin
  redis:
    database: 0
    host: 116.196.91.220
    port: 6379
    password:
    timeout: 100000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
       
logging:
  level:
    org.springframework: 
      data: DEBUG
      security: DEBUG
    com.hshw: DEBUG
    org.ibatis: INFO
  path: /logs
  
##mybatis
mybatis-plus: 
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.henede.admin.domain
  type-enums-package: com.henede.admin.domain.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    #序列接口实现类配置 实现IKeyGenerator
    #key-generator: com.hshw.jeicms.config.MybatisPlusKeyGenerator
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    meta-object-handler: com.henede.admin.config.MybatisPlusMetaHandler
    #逻辑删除SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


